### ISSUE TITLE
SignalR Send does not seem to be sending

### ISSUE THREAD

**Issue by ThyHG** [Pineapples/sh-boardgame#23]
https://github.com/Pineapples/sh-boardgame/blob/d05ec1f6d1f9e1ce61eeace504ac31e51deb0bb6/SecretHitler.API/Controllers/GameController.cs#L58

I do not get a reply from this when subscribed to 'GameInfo'.  I do however get an OK response from the http request. Any idea where this goes wrong?

If this is because of the addition of groups, then close the issue and let's fix it for the starting of the game only.

**Comment by Pineapples** [comment]
Not sure why you're not getting a reply, but that broadcast shouldn't be there in the first place. Will investigate why its not working

**Comment by Pineapples** [comment]
Investigated this, seems to send but not receive, when changing to send a message without data with a random string, it does seem to be received.

**Comment by Pineapples** [comment]
Closing issue because of fix in #24
